### ISSUE TITLE
Core dumped on run in k8s

### ISSUE THREAD

**Issue by lwsanty** [athenianco/athenian-api#10]
**steps to reproduce**
1) I took image `gcr.io/athenian-1/api:add-cd-21c2040`, built in travis, based on the PR https://github.com/athenianco/infrastructure/pull/2
2) running it inside the k8s
**result:** I receive `core dumped` error
**logs** these command are executed inside the pod
```
root@api-deployment-9c96897c-sc66s:/# python3 -m athenian.api --log-level=DEBUG --host=0.0.0.0 --port=8080 --db=postgresql://postgres:postgres@postgres-api-service:5432/api --ui=true
Illegal instruction (core dumped)
root@api-deployment-9c96897c-sc66s:/# python3 -m athenian.api --help
Illegal instruction (core dumped)
```
**note** when I use image that I built locally this problem is not reproduced, probably some problem with the environment of travis

**Comment by vmarkovtsev** [comment]
This is about a shitty CPU without AVX/AVX2 in Travis. We build the image on a CPU with AVX/AVX2, and run it on a different CPU without them. Can you please post `lscpu`

**Comment by vmarkovtsev** [comment]
Besides, can you please

```
apt update
apt install gdb python3-dbg
gdb --args python3 -m athenian.api --help
>>> r
>>> bt
```

**Comment by lwsanty** [comment]
```
root@api-deployment-9c96897c-mmgbp:/# lscpu
Architecture:                    x86_64
CPU op-mode(s):                  32-bit, 64-bit
Byte Order:                      Little Endian
Address sizes:                   46 bits physical, 48 bits virtual
CPU(s):                          1
On-line CPU(s) list:             0
Thread(s) per core:              1
Core(s) per socket:              1
Socket(s):                       1
NUMA node(s):                    1
Vendor ID:                       GenuineIntel
CPU family:                      6
Model:                           63
Model name:                      Intel(R) Xeon(R) CPU @ 2.30GHz
Stepping:                        0
CPU MHz:                         2300.000
BogoMIPS:                        4600.00
Hypervisor vendor:               KVM
Virtualization type:             full
L1d cache:                       32 KiB
L1i cache:                       32 KiB
L2 cache:                        256 KiB
L3 cache:                        45 MiB
NUMA node0 CPU(s):               0
Vulnerability L1tf:              Mitigation; PTE Inversion
Vulnerability Mds:               Mitigation; Clear CPU buffers; SMT Host state unknown
Vulnerability Meltdown:          Mitigation; PTI
Vulnerability Spec store bypass: Mitigation; Speculative Store Bypass disabled via prctl and seccomp
Vulnerability Spectre v1:        Mitigation; usercopy/swapgs barriers and __user pointer sanitization
Vulnerability Spectre v2:        Mitigation; Full generic retpoline, IBPB conditional, IBRS_FW, STIBP disabled, RSB filling
Flags:                           fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush mmx fxsr sse sse2 ss ht syscall nx pdpe1gb rdtscp lm const
                                 ant_tsc rep_good nopl xtopology nonstop_tsc cpuid tsc_known_freq pni pclmulqdq ssse3 fma cx16 pcid sse4_1 sse4_2 x2apic movbe popcnt aes x
                                 save avx f16c rdrand hypervisor lahf_lm abm invpcid_single pti ssbd ibrs ibpb stibp fsgsbase tsc_adjust bmi1 avx2 smep bmi2 erms invpcid x
                                 saveopt arat md_clear arch_capabilities
```

**Comment by lwsanty** [comment]
```python
(gdb) r
The program being debugged has been started already.
Start it from the beginning? (y or n) y
Starting program: /usr/bin/python3 -m athenian.api --help
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".

Program received signal SIGILL, Illegal instruction.
PyInit__multiarray_umath () at numpy/core/src/multiarray/multiarraymodule.c:4624
4624    numpy/core/src/multiarray/multiarraymodule.c: No such file or directory.
```
```python
(gdb) bt
#0  PyInit__multiarray_umath () at numpy/core/src/multiarray/multiarraymodule.c:4624
#1  0x000000000064658d in _PyImport_LoadDynamicModuleWithSpec (
    spec=<ModuleSpec(name='numpy.core._multiarray_umath', loader=<ExtensionFileLoader(name='numpy.core._multiarray_umath', path='/usr/local/lib/python3.7/dist-packages/numpy/core/_multiarray_umath.cpython-37m-x86_64-linux-gnu.so') at remote 0x7ffff45d9390>, origin='/usr/local/lib/python3.7/dist-packages/numpy/core/_multiarray_umath.cpython-37m-x86_64-linux-gnu.so', loader_state=None, submodule_search_locations=None, _set_fileattr=True, _cached=None) at remote 0x7ffff45d93d0>, fp=<optimized out>)
    at ../Python/importdl.c:159
#2  0x00000000006473e0 in _imp_create_dynamic_impl (module=<optimized out>, file=<optimized out>, 
    spec=<ModuleSpec(name='numpy.core._multiarray_umath', loader=<ExtensionFileLoader(name='numpy.core._multiarray_umath', path='/usr/local/lib/python3.7/dist-packages/numpy/core/_multiarray_umath.cpython-37m-x86_64-linux-gnu.so') at remote 0x7ffff45d9390>, origin='/usr/local/lib/python3.7/dist-packages/numpy/core/_multiarray_umath.cpython-37m-x86_64-linux-gnu.so', loader_state=None, submodule_search_locations=None, _set_fileattr=True, _cached=None) at remote 0x7ffff45d93d0>) at ../Python/import.c:2170
#3  _imp_create_dynamic (module=<optimized out>, args=<optimized out>, nargs=<optimized out>) at ../Python/clinic/import.c.h:289
#4  0x00000000005c8d61 in _PyMethodDef_RawFastCallDict (kwargs=<optimized out>, nargs=1, args=0x7ffff45d9368, self=<optimized out>, method=<optimized out>)
    at ../Objects/call.c:774
#5  _PyCFunction_FastCallDict (kwargs=<optimized out>, nargs=1, args=0x7ffff45d9368, func=<built-in method create_dynamic of module object at remote 0x7ffff78b2cb0>)
    at ../Objects/call.c:586
#6  PyCFunction_Call (func=<built-in method create_dynamic of module object at remote 0x7ffff78b2cb0>, 
    args=(<ModuleSpec(name='numpy.core._multiarray_umath', loader=<ExtensionFileLoader(name='numpy.core._multiarray_umath', path='/usr/local/lib/python3.7/dist-packages/numpy/core/_multiarray_umath.cpython-37m-x86_64-linux-gnu.so') at remote 0x7ffff45d9390>, origin='/usr/local/lib/python3.7/dist-packages/numpy/core/_multiarray_umath.cpython-37m-x86_64-linux-gnu.so', loader_state=None, submodule_search_locations=None, _set_fileattr=True, _cached=None) at remote 0x7ffff45d93d0>,), kwargs=<optimized out>)
    at ../Objects/call.c:791
#7  0x000000000053e5e2 in do_call_core (kwdict={}, 
    callargs=(<ModuleSpec(name='numpy.core._multiarray_umath', loader=<ExtensionFileLoader(name='numpy.core._multiarray_umath', path='/usr/local/lib/python3.7/dist-packages/numpy/core/_multiarray_umath.cpython-37m-x86_64-linux-gnu.so') at remote 0x7ffff45d9390>, origin='/usr/local/lib/python3.7/dist-packages/numpy/core/_multiarray_umath.cpython-37m-x86_64-linux-gnu.so', loader_state=None, submodule_search_locations=None, _set_fileattr=True, _cached=None) at remote 0x7ffff45d93d0>,), 
    func=<built-in method create_dynamic of module object at remote 0x7ffff78b2cb0>) at ../Python/ceval.c:4641
#8  _PyEval_EvalFrameDefault (f=<optimized out>, throwflag=<optimized out>) at ../Python/ceval.c:3191
#9  0x00000000005373a7 in PyEval_EvalFrameEx (throwflag=0, 
    f=Frame 0x7ffff45db210, for file <frozen importlib._bootstrap>, line 219, in _call_with_frames_removed (f=<built-in method create_dynamic of module object at remote 0x7ffff78b2cb0>, args=(<ModuleSpec(name='numpy.core._multiarray_umath', loader=<ExtensionFileLoader(name='numpy.core._multiarray_umath', path='/usr/local/lib/python3.7/dist-packages/numpy/core/_multiarray_umath.cpython-37m-x86_64-linux-gnu.so') at remote 0x7ffff45d9390>, origin='/usr/local/lib/python3.7/dist-packages/numpy/core/_multiarray_umath.cpython-37m-x86_64-linux-gnu.so', loader_state=None, submodule_search_locations=None, _set_fileattr=True, _cached=None) at remote 0x7ffff45d93d0>,), kwds={}))
    at ../Python/ceval.c:547
#10 _PyEval_EvalCodeWithName (_co=<optimized out>, globals=<optimized out>, locals=<optimized out>, args=<optimized out>, argcount=<optimized out>, 
    kwnames=<optimized out>, kwargs=0x7ffff765c590, kwcount=<optimized out>, kwstep=1, defs=0x0, defcount=0, kwdefs=0x0, closure=0x0, name='_call_with_frames_removed', 
    qualname='_call_with_frames_removed') at ../Python/ceval.c:3930
#11 0x00000000005c9358 in _PyFunction_FastCallKeywords (func=<optimized out>, stack=0x7ffff765c580, nargs=2, kwnames=<optimized out>) at ../Objects/call.c:433
#12 0x0000000000536640 in call_function (pp_stack=0x7fffffff5648, oparg=<optimized out>, kwnames=<optimized out>) at ../Python/ceval.c:4616
#13 0x000000000053d361 in _PyEval_EvalFrameDefault (f=<optimized out>, throwflag=<optimized out>) at ../Python/ceval.c:3093
#14 0x00000000005c905b in PyEval_EvalFrameEx (throwflag=0, 
    f=Frame 0x7ffff765c3f0, for file <frozen importlib._bootstrap_external>, line 1043, in create_module (self=<ExtensionFileLoader(name='numpy.core._multiarray_umath', path='/usr/local/lib/python3.7/dist-packages/numpy/core/_multiarray_umath.cpython-37m-x86_64-linux-gnu.so') at remote 0x7ffff45d9390>, spec=<ModuleSpec(name='numpy.core._multiarray_umath', loader=<...>, origin='/usr/local/lib/python3.7/dist-packages/numpy/core/_multiarray_umath.cpython-37m-x86_64-linux-gnu.so', loader_state=None, submodule_search_locations=None, _set_fileattr=True, _cached=None) at remote 0x7ffff45d93d0>)) at ../Python/ceval.c:547
--Type <RET> for more, q to quit, c to continue without paging--
```

**Comment by kuba--** [comment]
Does it mean that `multiarraymodule` is missed in Docker build?

**Comment by vmarkovtsev** [comment]
@lwsanty sorry I forgot to ask to send the output of gdb's command `layout asm`

**Comment by vmarkovtsev** [comment]
@kuba-- No, there is nothing missing. That's an artifact of `-march=native` while compiling numpy.

**Comment by se7entyse7en** [comment]
I didn't dig in depth, but could [this](https://cloud.google.com/kubernetes-engine/docs/how-to/min-cpu-platform) help?

**Comment by vmarkovtsev** [comment]
`layout asm` gives

```
  >│0x7ffff42fbd53 <PyInit__multiarray_umath+21955> vmovdqa64 0x1a4703(%rip),%xmm0        # 0x7ffff44a0460                                                           │
   │0x7ffff42fbd5d <PyInit__multiarray_umath+21965> movl   $0xb940000,0x8(%rax)                                                                                      │
   │0x7ffff42fbd64 <PyInit__multiarray_umath+21972> vmovaps %xmm0,0x218e14(%rip)        # 0x7ffff4514b80 <_npy_scalar_kinds_table>                                   │
   │0x7ffff42fbd6c <PyInit__multiarray_umath+21980> vmovdqa64 0x1a46fa(%rip),%xmm0        # 0x7ffff44a0470                                                           │
   │0x7ffff42fbd76 <PyInit__multiarray_umath+21990> mov    $0x110e,%r8d                                                                                              │
   │0x7ffff42fbd7c <PyInit__multiarray_umath+21996> mov    $0x505,%r9d                                                                                               │
   │0x7ffff42fbd82 <PyInit__multiarray_umath+22002> mov    $0xffffffff,%r10d                                                                                         │
   │0x7ffff42fbd88 <PyInit__multiarray_umath+22008> mov    $0x240,%edx
```

vmovdqa64 belongs to AVX512 o_O I am pretty sure that the system on which `numpy` was compiled does not support AVX512. Investigating this.
