### ISSUE TITLE
OAuthProblem exception hides the real issue with the claims

### ISSUE THREAD

**Issue by dpordomingo** [athenianco/athenian-api#76]
https://github.com/athenianco/athenian-api/blob/5554c0645a228436b44f079c085bb2a7a80d4de8/server/athenian/api/auth.py#L338

This new exception hides the details of the real problem, which can be either a wrong `audience`, or a wrong `issuer`.

The original exception really explains the concrete issue as it can be seen below, but we're shadowing that info with a generic message.

Here is the original exception, which clearly explains that the issue is with the `audience`

```
ERROR:4a42:connexion.apis.aiohttp_api:Error handling request
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/dist-packages/connexion/apis/aiohttp_api.py", line 50, in problems_middleware
    response = yield from handler(request)
  File "/usr/local/lib/python3.7/dist-packages/aiohttp/web_middlewares.py", line 109, in impl
    return await handler(request)
  File "/server/athenian/api/__init__.py", line 175, in with_db
    return await handler(request)
  File "/usr/local/lib/python3.7/dist-packages/connexion/decorators/coroutine_wrappers.py", line 23, in wrapper
    connexion_response = yield from connexion_response
  File "/server/athenian/api/auth.py", line 163, in wrapper
    await self._set_user(request.context, token_info["token"])
  File "/server/athenian/api/auth.py", line 289, in _set_user
    token_info = await self._extract_token(token)
  File "/server/athenian/api/auth.py", line 337, in _extract_token
    issuer="https://%s/" % self._domain,
  File "/usr/local/lib/python3.7/dist-packages/jose/jwt.py", line 172, in decode
    options=defaults)
  File "/usr/local/lib/python3.7/dist-packages/jose/jwt.py", line 495, in _validate_claims
    _validate_aud(claims, audience=audience)
  File "/usr/local/lib/python3.7/dist-packages/jose/jwt.py", line 357, in _validate_aud
    raise JWTClaimsError('Invalid audience')
jose.exceptions.JWTClaimsError: Invalid audience

```

**Comment by vmarkovtsev** [comment]
Thanks for reporting. Yep, let's not hide the exact error messages. I hope it will not damage security.
